nohup: ignoring input
Running simulation number: 2
------------------------------------------------------------------
Activating conda environment: vertex_model

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


Running simulations for parameter: push_out_force_strength
Running simulation with push_out_force_strength = 2.5
/home/gili/anaconda3/envs/vertex_model/lib/python3.11/site-packages/numpy/_core/getlimits.py:551: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)
Simulation Parameters: simulation_2
dt: 0.05
time_limit: 100
save_frame_interval: 10
Done.
Final window area: 124.6113823070045
Max velocity at t=10: 1.2251174887843428
Running simulation with push_out_force_strength = 2.6
/home/gili/anaconda3/envs/vertex_model/lib/python3.11/site-packages/numpy/_core/getlimits.py:551: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)
Simulation Parameters: simulation_2
dt: 0.05
time_limit: 100
save_frame_interval: 10
Done.
Final window area: 125.62187265833234
Max velocity at t=10: 1.2723987919891753
Running simulation with push_out_force_strength = 2.7
/home/gili/anaconda3/envs/vertex_model/lib/python3.11/site-packages/numpy/_core/getlimits.py:551: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)
Simulation Parameters: simulation_2
dt: 0.05
time_limit: 100
save_frame_interval: 10
Done.
Final window area: 126.6345554565284
Max velocity at t=10: 1.3193499463088574
Running simulation with push_out_force_strength = 2.8
/home/gili/anaconda3/envs/vertex_model/lib/python3.11/site-packages/numpy/_core/getlimits.py:551: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)
Simulation Parameters: simulation_2
dt: 0.05
time_limit: 100
save_frame_interval: 10
Done.
Final window area: 127.64923872658687
Max velocity at t=10: 1.3708170008264464
Running simulation with push_out_force_strength = 2.9
/home/gili/anaconda3/envs/vertex_model/lib/python3.11/site-packages/numpy/_core/getlimits.py:551: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)
Simulation Parameters: simulation_2
dt: 0.05
time_limit: 100
save_frame_interval: 10
Done.
Final window area: 128.66619695014938
Max velocity at t=10: 1.4202101356838925
Running simulation with push_out_force_strength = 3.0
/home/gili/anaconda3/envs/vertex_model/lib/python3.11/site-packages/numpy/_core/getlimits.py:551: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)
Simulation Parameters: simulation_2
dt: 0.05
time_limit: 100
save_frame_interval: 10
Done.
Final window area: 129.68535850994886
Max velocity at t=10: 1.4699891057223737
Running simulation with push_out_force_strength = 3.1
/home/gili/anaconda3/envs/vertex_model/lib/python3.11/site-packages/numpy/_core/getlimits.py:551: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)
Simulation Parameters: simulation_2
dt: 0.05
time_limit: 100
save_frame_interval: 10
Done.
Final window area: 130.7065952713302
Max velocity at t=10: 1.5206315465967601
Running simulation with push_out_force_strength = 3.2
/home/gili/anaconda3/envs/vertex_model/lib/python3.11/site-packages/numpy/_core/getlimits.py:551: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)
Simulation Parameters: simulation_2
dt: 0.05
time_limit: 100
save_frame_interval: 10
Done.
Final window area: 131.73025751620048
Max velocity at t=10: 1.569738940572541
Running simulation with push_out_force_strength = 3.3
/home/gili/anaconda3/envs/vertex_model/lib/python3.11/site-packages/numpy/_core/getlimits.py:551: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)
Simulation Parameters: simulation_2
dt: 0.05
time_limit: 100
save_frame_interval: 10
Done.
Final window area: 132.75605804897194
Max velocity at t=10: 1.6163257311303045
Running simulation with push_out_force_strength = 3.4
/home/gili/anaconda3/envs/vertex_model/lib/python3.11/site-packages/numpy/_core/getlimits.py:551: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)
Simulation Parameters: simulation_2
dt: 0.05
time_limit: 100
save_frame_interval: 10
Done.
Final window area: 133.78397469002644
Max velocity at t=10: 1.6671687787230551
Running simulation with push_out_force_strength = 3.5
/home/gili/anaconda3/envs/vertex_model/lib/python3.11/site-packages/numpy/_core/getlimits.py:551: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)
Simulation Parameters: simulation_2
dt: 0.05
time_limit: 100
save_frame_interval: 10
Done.
Final window area: 134.8142526830701
Max velocity at t=10: 1.7148283724151065
Results saved to results/simulation_2_final_results.txt
Done.
